set(GIT_COMMIT_COUNT 11110)
set(GIT_BRANCH D)
set(GIT_COMMIT develop)
set(GIT_VERSION "${GIT_COMMIT_COUNT}-${GIT_BRANCH}-${GIT_COMMIT}")
file(WRITE ${PROJECT_BINARY_DIR}/git_version
    "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${GIT_VERSION}"
)